### ISSUE TITLE
Bug with testing episodes

### ISSUE THREAD

**Issue by hnekoeiq** [chandar-lab/RLHive#246]
I believe this should be `<` rather than `<=`, no?

> https://github.com/chandar-lab/RLHive/blob/c5b1b77a3daf87aeb877e10c4f65bcd7e2bc1ff8/hive/runners/base.py#L159

**Comment by dapatil211** [comment]
Yes I think you're right, could you create the pr?

**Comment by dapatil211** [comment]
Closed by #281
