### ISSUE TITLE
pytorch version update ~=1.6 -> >=1.7

### ISSUE THREAD

**Issue by sriyash421** [chandar-lab/RLHive#273]
The code for distributional RL uses tensor.tile function from PyTorch which is available in stable releases of PyTorch >= 1.7. So the dependency needs to be updated. I am not sure how it went through the CI/CD.

**Comment by dapatil211** [comment]
Good catch. I think the version in the requirements.txt is different from the lowest version in the setup.py. The CI system right now is pretty basic, it just installs the packages in the requirements.txt and runs unit tests. The pytorch version in both requirements.txt and setup.py should be updated to 1.7.

**Comment by sriyash421** [comment]
My bad it's 1.8 and in the requirements.txt the version was already==1.8.0 so that is why all the checks passed. I have updated the version in setup.py. For building a better CI/CD I'll open up another issue to create a workflow which runs checks across versions.

**Comment by dapatil211** [comment]
Checking across all versions might get expensive. Maybe just two runs, one with all lowest versions of dependencies, and one with all highest?

**Comment by sriyash421** [comment]
Yes thats something can be done. I'll quickly review what the standard practice is and update.

**Comment by dapatil211** [comment]
The version has been updated
